/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pta_PTA */

#ifndef _Included_pta_PTA
#define _Included_pta_PTA
#ifdef __cplusplus
extern "C" {
#endif
#undef pta_PTA_serialVersionUID
#define pta_PTA_serialVersionUID 1LL
/*
 * Class:     pta_PTA
 * Method:    fit2DGauss
 * Signature: ([D[DI[I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_pta_PTA_fit2DGauss
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
