/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PTA_ */

#ifndef _Included_PTA_
#define _Included_PTA_
#ifdef __cplusplus
extern "C" {
#endif
#undef PTA__serialVersionUID
#define PTA__serialVersionUID 1LL
/*
 * Class:     PTA_
 * Method:    fit2DGauss
 * Signature: ([D[DI[I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_PTA_1_fit2DGauss
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
